const KEY="juaskuyy-demo-v1";
const demo={NikiRoom:{rooms:[{name:"Room A",status:"Terisi"},{name:"Room B",status:"Kosong"},{name:"Room C",status:"Terisi"}],income:[{desc:"Sewa Room A",amount:150000,date:"23 Agu 2026"},{desc:"Setoran teman",amount:500000,date:"22 Agu 2026"}],expense:[{desc:"Laundry",amount:100000,date:"22 Agu 2026"}],history:[]},VinzzRoom:{rooms:[{name:"Room 01",status:"Terisi"},{name:"Room 02",status:"Kosong"}],income:[{desc:"Sewa Room 01",amount:1200000,date:"23 Agu 2026"}],expense:[{desc:"Cleaning",amount:150000,date:"22 Agu 2026"}],history:[]}};
let db=JSON.parse(localStorage.getItem(KEY)||"null")||demo;
let profile=localStorage.getItem("juaskuyy-profile")||null;

const rupiah=n=>new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(n);
const save=()=>localStorage.setItem(KEY,JSON.stringify(db));
function login(){document.getElementById("app").innerHTML=`<main class="login"><section class="login-card"><div class="logo">🏠</div><h1>Rekapan Juaskuyy</h1><p class="muted">Kelola rekapan sewa room apartemen dengan rapi.</p><div class="profiles"><button class="profile" onclick="enter('NikiRoom')"><span class="icon">🌷</span><b>NikiRoom</b><small>Masuk ke profil NikiRoom</small></button><button class="profile" onclick="enter('VinzzRoom')"><span class="icon">🏙️</span><b>VinzzRoom</b><small>Masuk ke profil VinzzRoom</small></button></div></section></main>`}
function enter(p){profile=p;localStorage.setItem("juaskuyy-profile",p);dashboard()}
function logout(){profile=null;localStorage.removeItem("juaskuyy-profile");login()}
function dashboard(){
 const d=db[profile], inc=d.income.reduce((a,x)=>a+x.amount,0), out=d.expense.reduce((a,x)=>a+x.amount,0), final=inc-out;
 document.getElementById("app").innerHTML=`<main class="shell">
 <header class="topbar"><div><div class="brand">Rekapan Juaskuyy</div><div class="muted">${profile} · Periode aktif</div></div><div class="actions"><button class="btn light" onclick="switchProfile()">🔄 Switch</button><button class="btn" onclick="closing()">✓ Closing</button></div></header>
 <nav class="menu"><button class="btn dark">Dashboard</button><button class="btn light" onclick="showRooms()">🏠 Room</button><button class="btn light" onclick="showTransactions()">💰 Pemasukan</button><button class="btn light" onclick="showExpense()">💸 Pengeluaran</button><button class="btn light" onclick="showHistory()">🗂️ Riwayat</button><button class="btn light" onclick="downloadReport()">📸 Unduh Gambar</button></nav>
 <section class="hero"><h2>${profile}</h2><div class="muted">Rekapan sewa room apartemen · periode berjalan</div></section>
 <section class="stats"><div class="stat"><span>Total Pemasukan</span><strong>${rupiah(inc)}</strong></div><div class="stat"><span>Total Pengeluaran</span><strong>${rupiah(out)}</strong></div><div class="stat"><span>Final</span><strong>${rupiah(final)}</strong></div><div class="stat"><span>Jumlah Room</span><strong>${d.rooms.length}</strong></div></section>
 <section class="grid"><div class="card"><h3>Transaksi Terbaru</h3>${d.income.slice(-4).reverse().map(x=>`<div class="row"><div><b>${x.desc}</b><br><small class="muted">${x.date}</small></div><b class="money in">+${rupiah(x.amount)}</b></div>`).join("")||'<p class="muted">Belum ada transaksi.</p>'}</div>
 <div class="card"><h3>Status Room</h3>${d.rooms.map(x=>`<div class="row"><b>${x.name}</b><span class="pill">${x.status}</span></div>`).join("")}</div></section></main>`}
function switchProfile(){profile=profile==="NikiRoom"?"VinzzRoom":"NikiRoom";localStorage.setItem("juaskuyy-profile",profile);dashboard()}
function showRooms(){const d=db[profile];document.getElementById("app").querySelector(".shell").innerHTML+=`<section class="card section"><h3>🏠 Daftar ${profile}</h3>${d.rooms.map(x=>`<div class="row"><b>${x.name}</b><span class="pill">${x.status}</span></div>`).join("")}</section>`}
function showTransactions(){const d=db[profile];document.getElementById("app").querySelector(".shell").innerHTML+=`<section class="card section"><h3>💰 Pemasukan & Setoran</h3><div class="notice">Semua pemasukan tersimpan khusus untuk ${profile}.</div>${d.income.map(x=>`<div class="row"><div><b>${x.desc}</b><br><small class="muted">${x.date}</small></div><b class="money in">+${rupiah(x.amount)}</b></div>`).join("")}</section>`}
function showExpense(){const d=db[profile];document.getElementById("app").querySelector(".shell").innerHTML+=`<section class="card section"><h3>💸 Pengeluaran</h3>${d.expense.map(x=>`<div class="row"><div><b>${x.desc}</b><br><small class="muted">${x.date}</small></div><b class="money out">-${rupiah(x.amount)}</b></div>`).join("")}</section>`}
function showHistory(){const d=db[profile];document.getElementById("app").querySelector(".shell").innerHTML+=`<section class="card section"><h3>🗂️ Riwayat Closing</h3>${d.history.length?d.history.map((x,i)=>`<div class="row"><div><b>Periode ${i+1}</b><br><small class="muted">${x.date}</small></div><b>${rupiah(x.final)}</b></div>`).join(""):'<p class="muted">Belum ada closing.</p>'}</section>`}
function closing(){const d=db[profile],inc=d.income.reduce((a,x)=>a+x.amount,0),out=d.expense.reduce((a,x)=>a+x.amount,0);if(!confirm(`Closing ${profile}? Data periode aktif akan diarsipkan lalu dimulai dari 0.`))return;d.history.push({date:new Date().toLocaleString("id-ID"),rooms:structuredClone(d.rooms),income:structuredClone(d.income),expense:structuredClone(d.expense),final:inc-out});d.income=[];d.expense=[];save();dashboard()}
function downloadReport(){const d=db[profile],inc=d.income.reduce((a,x)=>a+x.amount,0),out=d.expense.reduce((a,x)=>a+x.amount,0);const text=`REKAPAN JUASKUYY\n${profile}\n\nROOM\n${d.rooms.map(x=>`${x.name} - ${x.status}`).join("\n")}\n\nPEMASUKAN\n${d.income.map(x=>`${x.date} | ${x.desc} | ${rupiah(x.amount)}`).join("\n")}\n\nPENGELUARAN\n${d.expense.map(x=>`${x.date} | ${x.desc} | ${rupiah(x.amount)}`).join("\n")}\n\nTOTAL PEMASUKAN: ${rupiah(inc)}\nTOTAL PENGELUARAN: ${rupiah(out)}\nFINAL: ${rupiah(inc-out)}`;const blob=new Blob([text],{type:"text/plain"}),a=document.createElement("a");a.href=URL.createObjectURL(blob);a.download=`Rekapan-${profile}.txt`;a.click()}
profile?dashboard():login();
