const app=document.getElementById("app");let profile=null,cache=null;
const rupiah=n=>new Intl.NumberFormat("id-ID",{style:"currency",currency:"IDR",maximumFractionDigits:0}).format(n||0);
const esc=s=>String(s??"").replace(/[&<>"']/g,m=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[m]));
async function api(u,o){const r=await fetch(u,o),d=await r.json();if(!r.ok)throw Error(d.error||"Terjadi kesalahan");return d}
function toast(s){const e=document.createElement("div");e.className="toast";e.textContent=s;document.body.append(e);setTimeout(()=>e.remove(),2200)}
function modal(title,body){document.body.insertAdjacentHTML("beforeend",`<div class="modal-back" id="modal"><section class="modal"><div class="modal-head"><h3>${title}</h3><button class="btn light" onclick="closeModal()">✕</button></div>${body}</section></div>`)}
function closeModal(){document.getElementById("modal")?.remove()}
function dateFmt(x){if(!x)return"-";const [y,m,d]=x.split("-");return `${d}-${m}-${y}`}
async function login(){let d;try{d=await api("/api?action=profiles")}catch(e){app.innerHTML=`<main class="login"><section class="login-card"><div class="logo">🏠</div><h1>Rekapan Juaskuyy</h1><p class="muted">Database/API belum siap atau deployment belum terbaru.</p><p>${esc(e.message)}</p></section></main>`;return}
app.innerHTML=`<main class="login"><section class="login-card"><div class="logo">🏠</div><h1>Rekapan Juaskuyy</h1><p class="muted">Rekapan sewa room apartemen</p><div class="profiles">${d.profiles.map(p=>`<button class="profile" onclick="choose('${p.id}',${p.has_pin})"><span class="logo">${p.id==="nikiroom"?"🌷":"🏙️"}</span><b>${esc(p.name)}</b><small>${p.has_pin?"Masukkan PIN":"Buat PIN pertama kali"}</small></button>`).join("")}</div></section></main>`}
function choose(id,has){modal(has?"🔐 Login "+(id==="nikiroom"?"NikiRoom":"VinzzRoom"):"🔐 Buat PIN",`<form class="form" onsubmit="doLogin(event,'${id}')"><input name="pin" type="password" inputmode="numeric" minlength="4" placeholder="${has?"PIN":"Buat PIN minimal 4 digit"}" required><button class="btn dark">${has?"Masuk":"Simpan PIN & Masuk"}</button></form>`)}
async function doLogin(e,id){e.preventDefault();try{const f=new FormData(e.target);await api("/api",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"login",profile:id,pin:f.get("pin")})});closeModal();profile=id;localStorage.setItem("juaskuyy-profile",id);await dashboard()}catch(x){toast(x.message)}}
async function logout(){await api("/api",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"logout"})}).catch(()=>{});localStorage.removeItem("juaskuyy-profile");profile=null;login()}
async function dashboard(){cache=await api("/api?action=dashboard");profile=cache.profile.id;render(`<section class="hero"><h2>${esc(cache.profile.name)}</h2><div class="muted">Shift ${cache.period.period_number}${cache.period.start_date?` · ${dateFmt(cache.period.start_date)}–${dateFmt(cache.period.end_date)}`:" · Periode aktif"}</div></section><section class="stats"><div class="stat"><span>Pemasukan</span><strong>${rupiah(cache.income)}</strong></div><div class="stat"><span>Pengeluaran</span><strong>${rupiah(cache.expense)}</strong></div><div class="stat"><span>Total Shift</span><strong>${rupiah(cache.final)}</strong></div><div class="stat"><span>Room</span><strong>${cache.rooms.length}</strong></div></section><section class="grid"><div class="card"><h3>🏠 Cash per Room</h3>${cache.rooms.map(r=>`<div class="room-box"><b>${esc(r.name)}</b><div class="big">${rupiah(r.cash)}</div><small class="muted">Masuk ${rupiah(r.income)} · Keluar ${rupiah(r.expense)}</small></div>`).join("")||'<div class="empty">Belum ada room.</div>'}</div><div class="card"><h3>Transaksi Terbaru</h3>${cache.transactions.slice(0,8).map(txRow).join("")||'<div class="empty">Belum ada transaksi.</div>'}</div></section>`)}
function render(content){app.innerHTML=`<main class="shell"><header class="topbar"><div><div class="brand">Rekapan Juaskuyy</div><div class="muted">${esc(cache?.profile?.name||"")}</div></div><div class="actions"><button class="btn light" onclick="switchProfile()">🔄 Switch</button><button class="btn" onclick="closingModal()">🔒 Ganti Shift</button></div></header><nav class="menu"><button class="btn dark" onclick="dashboard()">Dashboard</button><button class="btn light" onclick="rooms()">🏠 Room</button><button class="btn light" onclick="income()">💰 Pemasukan</button><button class="btn light" onclick="expense()">💸 Pengeluaran</button><button class="btn light" onclick="transactions()">📋 Transaksi</button><button class="btn light" onclick="history()">🗂️ Riwayat</button><button class="btn light" onclick="monthly()">📊 Bulanan</button><button class="btn light" onclick="settings()">⚙️ Pengaturan</button><button class="btn light" onclick="logout()">Keluar</button></nav>${content}</main>`}
async function switchProfile(){await logout()}
function txRow(t){return `<div class="row"><span><b>${esc(t.description)}</b><br><small class="muted">${dateFmt(t.transaction_date)}${t.room_name?" · "+esc(t.room_name):""}</small></span><b class="${t.type==="income"?"in":"out"}">${t.type==="income"?"+":"-"}${rupiah(t.amount)}</b></div>`}
function rooms(){render(`<section class="card section"><h3>🏠 Room</h3><form class="form" onsubmit="addRoom(event)"><div class="form-grid"><input name="name" placeholder="Nama / nomor room" required><select name="status"><option>Kosong</option><option>Terisi</option></select></div><button class="btn dark">+ Tambah Room</button></form><div class="section">${cache.rooms.map(r=>`<div class="row"><span><b>${esc(r.name)}</b><br><small>Cash ${rupiah(r.cash)}</small></span><span><span class="pill">${r.status}</span> <button class="btn danger" onclick="delRoom(${r.id})">🗑️</button></span></div>`).join("")||'<div class="empty">Belum ada room.</div>'}</div></section>`)}
async function addRoom(e){e.preventDefault();const f=new FormData(e.target);await api("/api",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"room",name:f.get("name"),status:f.get("status")})});toast("Room ditambahkan");dashboard()}
async function delRoom(id){if(!confirm("Hapus room? Transaksi lama tidak ikut dihapus."))return;await api("/api",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"delete_room",id})});toast("Room dihapus");dashboard()}
function income(edit=null){const t=edit||{};modal(edit?"✏️ Edit Pemasukan":"💰 Pemasukan",txForm("income",t))}
function expense(edit=null){const t=edit||{};modal(edit?"✏️ Edit Pengeluaran":"💸 Pengeluaran",txForm("expense",t))}
function txForm(type,t){const rooms=cache.rooms.map(r=>`<option value="${r.id}" ${String(t.room_id||"")===String(r.id)?"selected":""}>${esc(r.name)}</option>`).join("");return `<form class="form" onsubmit="saveTx(event,'${type}',${t.id||0})">${type==="income"?`<select name="source"><option value="room_rental" ${t.source_type==="room_rental"?"selected":""}>Sewa Room</option><option value="friend_deposit" ${t.source_type==="friend_deposit"?"selected":""}>Setoran Teman</option><option value="other_income" ${t.source_type==="other_income"?"selected":""}>Pemasukan Lain</option></select><select name="room"><option value="">${t.source_type==="room_rental"?"Pilih Room":"Tanpa room"}</option>${rooms}</select>`:""}<input name="desc" value="${esc(t.description||"")}" placeholder="Keterangan" required><div class="form-grid"><input name="amount" type="number" min="0" value="${t.amount||""}" placeholder="Nominal" required><input name="date" type="date" value="${t.transaction_date||new Date().toISOString().slice(0,10)}" required></div><input name="time" type="time" value="${t.transaction_time||""}"><textarea name="notes" placeholder="Catatan">${esc(t.notes||"")}</textarea><button class="btn dark">Simpan</button></form>`}
async function saveTx(e,type,id){e.preventDefault();const f=new FormData(e.target),source=type==="income"?f.get("source"):"expense",room=f.get("room")||null;if(type==="income"&&source==="room_rental"&&!room){toast("Pilih room untuk Sewa Room");return}const body={action:id?"edit_transaction":"transaction",id, type,source_type:source,room_id:room,description:f.get("desc"),amount:f.get("amount"),date:f.get("date"),time:f.get("time"),notes:f.get("notes")};try{await api("/api",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify(body)});closeModal();toast("Tersimpan");dashboard()}catch(x){toast(x.message)}}
function transactions(){let list=cache.transactions;render(`<section class="card section"><h3>📋 Transaksi</h3><div class="searchbar"><input id="q" placeholder="Cari keterangan / room" oninput="filterTx()"><select id="ft"><option value="">Semua</option><option value="income">Pemasukan</option><option value="expense">Pengeluaran</option></select><input id="fd" type="date"><button class="btn" onclick="filterTx()">Cari</button></div><div id="txlist">${list.map(txActionRow).join("")}</div></section>`)}
function txActionRow(t){return `<div class="row"><span><b>${esc(t.description)}</b><br><small class="muted">${dateFmt(t.transaction_date)}${t.room_name?" · "+esc(t.room_name):""}</small></span><span><b class="${t.type==="income"?"in":"out"}">${t.type==="income"?"+":"-"}${rupiah(t.amount)}</b> <button class="btn light" onclick='editTx(${JSON.stringify(t).replace(/'/g,"&#39;")})'>✏️</button> <button class="btn danger" onclick="delTx(${t.id})">🗑️</button></span></div>`}
function filterTx(){const q=(document.getElementById("q")?.value||"").toLowerCase(),ft=document.getElementById("ft")?.value||"",fd=document.getElementById("fd")?.value||"";const list=cache.transactions.filter(t=>(!q||(t.description+" "+(t.room_name||"")).toLowerCase().includes(q))&&(!ft||t.type===ft)&&(!fd||t.transaction_date===fd));document.getElementById("txlist").innerHTML=list.map(txActionRow).join("")||'<div class="empty">Tidak ada transaksi.</div>'}
function editTx(t){t.type==="income"?income(t):expense(t)}
async function delTx(id){if(!confirm("Hapus transaksi ini?"))return;await api("/api",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"delete_transaction",id})});toast("Transaksi dihapus");dashboard()}
function closingModal(){modal("🔒 Ganti Shift",`<div class="notice">Shift ${cache.period.period_number} · Total saat ini <b>${rupiah(cache.final)}</b></div><form class="form" onsubmit="doClosing(event)"><div class="form-grid"><label>Mulai<input name="start" type="date" required></label><label>Selesai<input name="end" type="date" required></label></div><button class="btn dark">Tutup Shift & Mulai Shift Berikutnya</button></form>`)}
async function doClosing(e){e.preventDefault();const f=new FormData(e.target);if(f.get("end")<f.get("start")){toast("Tanggal selesai tidak boleh sebelum tanggal mulai");return}if(!confirm(`Tutup Shift ${cache.period.period_number}?`))return;await api("/api",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"closing",start_date:f.get("start"),end_date:f.get("end")})});closeModal();toast("Shift berhasil ditutup");dashboard()}
async function history(){const d=await api("/api?action=history");render(`<section class="card section"><h3>🗂️ Riwayat Shift</h3>${d.history.map(h=>`<div class="row"><span><b>Shift ${h.period_number}</b><br><small class="muted">${dateFmt(h.start_date)}–${dateFmt(h.end_date)}</small></span><span><b>${rupiah(h.final_amount)}</b><br><button class="btn light" onclick="shift(${h.id})">Detail</button> <button class="btn light" onclick="shareShift(${h.id})">💬 WA</button> <button class="btn light" onclick="exportShift(${h.id})">📸</button> <button class="btn danger" onclick="deleteHistory(${h.id})">🗑️</button></span></div>`).join("")||'<div class="empty">Belum ada riwayat shift.</div>'}</section>`)}
async function shift(id){const d=await api("/api?action=shift&id="+id);render(`<section class="card section"><div class="actions"><button class="btn light" onclick="history()">← Kembali</button><button class="btn" onclick="shareShift(${id})">💬 Share WhatsApp</button><button class="btn" onclick="exportShift(${id})">📸 Unduh PNG</button></div><div id="shift-report" class="section"><h2>Shift ${d.period.period_number} · ${esc(cache.profile.name)}</h2><p class="muted">${dateFmt(d.period.start_date)} – ${dateFmt(d.period.end_date)}</p><div class="stats"><div class="stat"><span>Pemasukan</span><strong>${rupiah(d.period.total_income)}</strong></div><div class="stat"><span>Pengeluaran</span><strong>${rupiah(d.period.total_expense)}</strong></div><div class="stat"><span>Total Shift</span><strong>${rupiah(d.period.final_amount)}</strong></div><div class="stat"><span>Transaksi</span><strong>${d.transactions.length}</strong></div></div><h3 class="section">🏠 Cash per Room</h3>${d.rooms.map(r=>`<div class="room-box"><b>${esc(r.room_name)}</b><div class="big">${rupiah(r.cash_amount)}</div><small>${esc(r.room_status)}</small></div>`).join("")||'<div class="empty">Tidak ada snapshot room.</div>'}<h3 class="section">📋 Transaksi</h3>${d.transactions.map(txRow).join("")}</div></section>`)}
async function deleteHistory(id){if(!confirm("Hapus riwayat shift ini secara permanen? Transaksi dan snapshot cash shift ini ikut dihapus."))return;await api("/api",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"delete_history",id})});toast("Riwayat dihapus");history()}
async function shareShift(id){const d=await api("/api?action=shift&id="+id),p=d.period;let text=`*Rekapan Juaskuyy*\\n*${cache.profile.name} · Shift ${p.period_number}*\\n${dateFmt(p.start_date)}–${dateFmt(p.end_date)}\\n\\n💰 Pemasukan: ${rupiah(p.total_income)}\\n💸 Pengeluaran: ${rupiah(p.total_expense)}\\n💵 Total Shift: ${rupiah(p.final_amount)}\\n\\n🏠 Cash per Room:\\n${d.rooms.map(r=>`• ${r.room_name}: ${rupiah(r.cash_amount)}`).join("\\n")||"• Tidak ada room"}\\n\\n📋 ${d.transactions.length} transaksi`;location.href="https://wa.me/?text="+encodeURIComponent(text)}
async function exportShift(id){const d=await api("/api?action=shift&id="+id),p=d.period;const c=document.createElement("canvas"),ctx=c.getContext("2d");c.width=1080;c.height=1200;ctx.fillStyle="#f7f2ee";ctx.fillRect(0,0,c.width,c.height);ctx.fillStyle="#5b4140";ctx.font="bold 48px Arial";ctx.fillText("Rekapan Juaskuyy",60,80);ctx.font="bold 34px Arial";ctx.fillText(`${cache.profile.name} · Shift ${p.period_number}`,60,140);ctx.font="24px Arial";ctx.fillText(`${dateFmt(p.start_date)} – ${dateFmt(p.end_date)}`,60,180);ctx.fillStyle="#fffdfb";ctx.fillRect(50,220,980,250);ctx.fillStyle="#3d3330";ctx.font="bold 26px Arial";ctx.fillText("Pemasukan",80,270);ctx.fillText("Pengeluaran",400,270);ctx.fillText("Total Shift",720,270);ctx.font="bold 30px Arial";ctx.fillText(rupiah(p.total_income),80,320);ctx.fillText(rupiah(p.total_expense),400,320);ctx.fillText(rupiah(p.final_amount),720,320);ctx.font="bold 30px Arial";ctx.fillText("Cash per Room",60,530);let y=580;ctx.font="24px Arial";for(const r of d.rooms){ctx.fillStyle="#fff";ctx.fillRect(50,y-32,980,62);ctx.fillStyle="#3d3330";ctx.fillText(r.room_name,75,y);ctx.fillText(rupiah(r.cash_amount),760,y);y+=78;if(y>1080)break}const a=document.createElement("a");a.href=c.toDataURL("image/png");a.download=`Rekapan-${cache.profile.name}-Shift-${p.period_number}.png`;a.click();toast("PNG berhasil dibuat")}
async function monthly(){const month=new Date().toISOString().slice(0,7),d=await api("/api?action=monthly&month="+month);const days={};d.transactions.forEach(t=>{days[t.transaction_date]=(days[t.transaction_date]||{i:0,e:0});days[t.transaction_date][t.type==="income"?"i":"e"]+=t.amount});const bars=Object.entries(days).slice(-14).map(([day,x])=>`<div class="bar"><span class="inbar" style="height:${Math.max(8,Math.min(140,x.i/10000))}px"></span><span class="outbar" style="height:${Math.max(8,Math.min(140,x.e/10000))}px"></span><label>${day.slice(-2)}</label></div>`).join("");render(`<section class="card section"><h3>📊 Rekap Bulanan · ${month}</h3><div class="stats"><div class="stat"><span>Pemasukan</span><strong>${rupiah(d.income)}</strong></div><div class="stat"><span>Pengeluaran</span><strong>${rupiah(d.expense)}</strong></div><div class="stat"><span>Final</span><strong>${rupiah(d.final)}</strong></div><div class="stat"><span>Transaksi</span><strong>${d.transactions.length}</strong></div></div><h3 class="section">Grafik Harian</h3><div class="chart">${bars||'<div class="empty">Belum ada data.</div>'}</div><div class="actions section"><button class="btn" onclick="shareMonthly('${month}')">💬 Share WhatsApp</button><button class="btn" onclick="exportMonthly('${month}')">📸 Unduh PNG</button></div></section>`)}
async function shareMonthly(month){const d=await api("/api?action=monthly&month="+month);location.href="https://wa.me/?text="+encodeURIComponent(`*Rekapan Juaskuyy*\\n*${cache.profile.name} · ${month}*\\n\\n💰 Pemasukan: ${rupiah(d.income)}\\n💸 Pengeluaran: ${rupiah(d.expense)}\\n💵 Final: ${rupiah(d.final)}\\n📋 ${d.transactions.length} transaksi`)}
async function exportMonthly(month){const d=await api("/api?action=monthly&month="+month),c=document.createElement("canvas"),ctx=c.getContext("2d");c.width=1080;c.height=800;ctx.fillStyle="#f7f2ee";ctx.fillRect(0,0,c.width,c.height);ctx.fillStyle="#5b4140";ctx.font="bold 48px Arial";ctx.fillText("Rekapan Juaskuyy",60,90);ctx.font="bold 32px Arial";ctx.fillText(`${cache.profile.name} · ${month}`,60,145);ctx.font="bold 30px Arial";ctx.fillStyle="#3d3330";ctx.fillText(`Pemasukan  ${rupiah(d.income)}`,70,250);ctx.fillText(`Pengeluaran  ${rupiah(d.expense)}`,70,320);ctx.fillText(`Final  ${rupiah(d.final)}`,70,390);const a=document.createElement("a");a.href=c.toDataURL("image/png");a.download=`Rekap-${cache.profile.name}-${month}.png`;a.click()}
async function settings(){render(`<section class="card section"><h3>⚙️ Pengaturan</h3><div class="actions"><button class="btn" onclick="pinModal()">🔐 Ganti PIN</button><button class="btn" onclick="backup()">💾 Backup Data</button></div><p class="muted">Backup berisi data profil, shift, room, transaksi, dan snapshot closing profil ini.</p></section>`)}
function pinModal(){modal("🔐 Ganti PIN",`<form class="form" onsubmit="changePin(event)"><input name="old" type="password" inputmode="numeric" placeholder="PIN lama" required><input name="new" type="password" inputmode="numeric" minlength="4" placeholder="PIN baru minimal 4 digit" required><button class="btn dark">Ganti PIN</button></form>`)}
async function changePin(e){e.preventDefault();const f=new FormData(e.target);try{await api("/api",{method:"POST",headers:{"content-type":"application/json"},body:JSON.stringify({action:"change_pin",old_pin:f.get("old"),new_pin:f.get("new")})});closeModal();toast("PIN berhasil diganti")}catch(x){toast(x.message)}}
async function backup(){const d=await api("/api?action=backup"),a=document.createElement("a");a.href=URL.createObjectURL(new Blob([JSON.stringify(d,null,2)],{type:"application/json"}));a.download=`Backup-${cache.profile.name}-${new Date().toISOString().slice(0,10)}.json`;a.click();toast("Backup diunduh")}
(async()=>{try{const s=await api("/api?action=session");if(s.logged_in){profile=s.profile.id;await dashboard()}else login()}catch(e){login()}})();
